"""Grounded, reusable summaries created when policy documents are ingested."""

import re

from langchain_core.prompts import ChatPromptTemplate
from langchain_google_genai import ChatGoogleGenerativeAI
from pydantic import BaseModel, Field

from app.core.config import settings

MAX_SUMMARY_SOURCE_CHARS = 60_000
MAX_EXTRACTIVE_CHARS = 1_200


class PolicySummaryError(RuntimeError):
    """A policy summary could not be generated by the configured model."""


class PolicySummary(BaseModel):
    summary: str = Field(min_length=20, max_length=2_500)


SUMMARY_PROMPT = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            """Create a concise employee-facing summary using only the supplied policy text.
Cover the policy's purpose, key rules, eligibility or limits, and required employee
actions when present. Do not invent missing details. Use short paragraphs or bullets
and keep the summary under 180 words.""",
        ),
        (
            "human",
            "Policy title: {title}\nCategory: {category}\n\nPolicy text:\n{content}",
        ),
    ]
)


def build_extractive_summary(texts: list[str]) -> str:
    """Create a bounded grounded fallback when model generation is unavailable."""
    normalized = re.sub(r"\s+", " ", " ".join(texts)).strip()
    if len(normalized) <= MAX_EXTRACTIVE_CHARS:
        return normalized
    shortened = normalized[:MAX_EXTRACTIVE_CHARS].rsplit(" ", 1)[0].rstrip(" ,;:")
    return f"{shortened}…"


async def generate_policy_summary(
    title: str, category: str, texts: list[str]
) -> str:
    if not settings.gemini_api_key or not settings.gemini_api_key.get_secret_value().strip():
        raise PolicySummaryError("GEMINI_API_KEY is not configured.")
    content = "\n\n".join(texts)[:MAX_SUMMARY_SOURCE_CHARS]
    model = ChatGoogleGenerativeAI(
        model=settings.rag_generation_model,
        google_api_key=settings.gemini_api_key,
        temperature=0,
        max_retries=settings.rag_generation_max_retries,
        request_timeout=settings.rag_generation_timeout_seconds,
    )
    chain = SUMMARY_PROMPT | model.with_structured_output(
        PolicySummary, method="json_schema"
    )
    try:
        result = await chain.ainvoke(
            {"title": title, "category": category, "content": content}
        )
        summary = result.summary.strip()
        if not summary:
            raise ValueError("The generated policy summary was empty.")
    except Exception as exc:
        raise PolicySummaryError("Policy summary generation failed.") from exc
    return summary
