"""add employee photo_url

Revision ID: 0d2ad9b36145
Revises: 1e9829fd0179
Create Date: 2026-09-22 15:17:09.166162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d2ad9b36145'
down_revision: Union[str, Sequence[str], None] = '1e9829fd0179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('photo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'photo_url')
    # ### end Alembic commands ###
