"""add employee profile columns

Revision ID: d14130037fee
Revises: 0d2ad9b36145
Create Date: 2026-09-22 16:10:53.875140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd14130037fee'
down_revision: Union[str, Sequence[str], None] = '0d2ad9b36145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('employee_code', sa.String(length=20), nullable=True))
    op.add_column('employees', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('employees', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('employees', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('emergency_contact', sa.String(length=20), nullable=True))
    op.add_column('employees', sa.Column('bank_name', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('account_number', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('ifsc_code', sa.String(length=20), nullable=True))
    op.add_column('employees', sa.Column('id_proof_type', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('id_proof_number', sa.String(length=100), nullable=True))
    op.create_unique_constraint("uq_employees_employee_code", 'employees', ['employee_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_employees_employee_code", 'employees', type_='unique')
    op.drop_column('employees', 'id_proof_number')
    op.drop_column('employees', 'id_proof_type')
    op.drop_column('employees', 'ifsc_code')
    op.drop_column('employees', 'account_number')
    op.drop_column('employees', 'bank_name')
    op.drop_column('employees', 'emergency_contact')
    op.drop_column('employees', 'city')
    op.drop_column('employees', 'address')
    op.drop_column('employees', 'gender')
    op.drop_column('employees', 'date_of_birth')
    op.drop_column('employees', 'employee_code')
    # ### end Alembic commands ###
